version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"

    default_assignees:
      - "lucasmazza"
      - "philss"
      - "ruan-brandao"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
